### ISSUE TITLE
Server crash using Icarian Flight Scroll

### ISSUE THREAD

**Issue by BillyRising** [Boyos999/AdditionalSpawnSystem#2]
Anytime i use an Icarian flight scroll the server crashes.

Certainly has to do with loading things really fast.

[ERR]: ...ver\scripts\custom\AdditionalSpawnSystem\spawnSystem.lua:333: attempt to index a nil value

**Comment by Boyos999** [comment]
@BillyRising I just made an update that should fix this: https://github.com/Boyos999/AdditionalSpawnSystem/commit/4827d17bf3a236e5273c2d5327ec362e9119cf2c

Let me know if you're still getting crashes after updating
